# Generated by Django 5.2.3 on 2025-06-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, verbose_name='Número da Nota')),
                ('empresa', models.CharField(blank=True, max_length=100, verbose_name='Empresa')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('mes_entrada', models.CharField(blank=True, help_text='Formato: MM/YYYY', max_length=7, verbose_name='Mês de Entrada')),
                ('arquivo', models.FileField(upload_to='notas_fiscais/', verbose_name='Arquivo PDF')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
            ],
        ),
    ]
