# Generated by Django 4.2.11 on 2025-06-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.CharField(max_length=50)),
                ('bin', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField()),
                ('onde_foi_usado', models.CharField(max_length=255)),
                ('ordem', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
                ('unit', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
