# Generated by Django 5.2.3 on 2025-07-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi_pendente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiPendenteSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveIntegerField(unique=True)),
                ('valor_pendente', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='GiPendente',
        ),
    ]
