# Generated by Django 5.2.3 on 2025-07-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi_pendente', '0004_gipendentesemana_mes_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiPendenteMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], max_length=10, unique=True)),
                ('ano', models.PositiveIntegerField(default=2025)),
                ('gi_realizado', models.FloatField(default=0)),
                ('gi_devido', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='GiPendenteSemana',
        ),
    ]
