# Generated by Django 5.2.3 on 2025-07-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi_pendente', '0005_gipendentemes_delete_gipendentesemana'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiPendenteSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('gi_realizado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gi_devido', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='GiPendenteMes',
        ),
    ]
