# Generated by Django 5.2.3 on 2025-07-05 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gi_pendente', '0006_gipendentesemana_delete_gipendentemes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gipendentesemana',
            name='ano',
        ),
    ]
