# Generated by Django 4.2.11 on 2025-07-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi_pendente', '0007_remove_gipendentesemana_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='gipendentesemana',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
