# Generated by Django 4.2.11 on 2025-07-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi_pendente', '0008_gipendentesemana_data_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gipendentesemana',
            name='data_atualizacao',
            field=models.DateTimeField(verbose_name='Data de Atualização'),
        ),
    ]
