# Generated by Django 4.2.11 on 2025-06-26 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PM05Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_envio', models.CharField(max_length=50, verbose_name='Catalog de Envio')),
                ('catalog_ersa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Catalog ERSA')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('fornecedor_enviado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedor Enviado')),
                ('codigo_supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Supplier')),
                ('data_envio', models.DateField(verbose_name='Data de Envio para Fornecedor')),
                ('numero_invoice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da Invoice')),
                ('numero_pm05', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número PM05')),
                ('nf_saida', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nota Fiscal de Saída')),
                ('nf_retorno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nota de Retorno')),
                ('obs1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Obs 1')),
                ('obs2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Obs 2')),
                ('obs3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Obs 3')),
            ],
        ),
        migrations.CreateModel(
            name='PM05Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pm05_fotos/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='pm05.pm05item')),
            ],
        ),
        migrations.CreateModel(
            name='PM05Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='pm05_arquivos/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='pm05.pm05item')),
            ],
        ),
    ]
