# Generated by Django 4.2.11 on 2025-06-22 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do solicitante')),
                ('descricao', models.TextField(verbose_name='Descrição detalhada')),
                ('catalogo', models.CharField(max_length=50, verbose_name='Catálogo')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('etapa', models.CharField(choices=[('aberto', 'Aberto'), ('cotado', 'Cotado'), ('pr', 'PR Criada'), ('finalizado', 'Finalizado')], default='aberto', max_length=20, verbose_name='Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa')),
                ('previsao_entrega', models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='demandas.demanda')),
            ],
        ),
    ]
