# Generated by Django 4.2.11 on 2025-06-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='demanda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='demandas.demanda'),
        ),
    ]
