# Generated by Django 4.2.11 on 2025-06-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0002_alter_pedido_demanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='informacao',
            field=models.TextField(blank=True, null=True, verbose_name='PO'),
        ),
    ]
