# Generated by Django 4.2.11 on 2025-07-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0003_pedido_informacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='catalogo',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Catalog'),
        ),
    ]
