# Generated by Django 4.2.11 on 2025-07-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0004_alter_demanda_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='cotacao_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cotacoes/', verbose_name='Cotação (PDF)'),
        ),
    ]
