# Generated by Django 5.2.3 on 2025-06-25 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ativo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('catalog', models.CharField(max_length=50)),
                ('local_armazenamento', models.CharField(max_length=100)),
                ('data_inventario', models.DateField()),
                ('obs1', models.CharField(blank=True, max_length=255, null=True)),
                ('obs2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='ativos_fotos/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ativos.ativo')),
            ],
        ),
    ]
